packages:
  - apps/*
  - packages/*

catalog:
  '@node-rs/argon2': ^2.0.2
  '@trpc/client': ^11.17.0
  '@trpc/server': ^11.17.0
  '@types/node': ^22.19.19
  '@types/react-dom': ^19.2.3
  better-auth: 1.6.9
  date-fns: ^4.1.0
  dotenv: ^17.4.2
  next-themes: ^0.4.6
  superjson: ^2.2.6
  typescript: ^6.0.3
  uuid: ^14.0.0
  zod: ^4.4.3
