/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as coreDashboardRouteRouteImport } from './routes/(core)/dashboard/route'
import { Route as coreDashboardIndexRouteImport } from './routes/(core)/dashboard/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as coreDashboardTechStackIndexRouteImport } from './routes/(core)/dashboard/tech-stack/index'
import { Route as coreDashboardSocialLinksIndexRouteImport } from './routes/(core)/dashboard/social-links/index'
import { Route as coreDashboardSeoIndexRouteImport } from './routes/(core)/dashboard/seo/index'
import { Route as coreDashboardResumeIndexRouteImport } from './routes/(core)/dashboard/resume/index'
import { Route as coreDashboardProjectsIndexRouteImport } from './routes/(core)/dashboard/projects/index'
import { Route as coreDashboardHeroIndexRouteImport } from './routes/(core)/dashboard/hero/index'
import { Route as coreDashboardExperienceIndexRouteImport } from './routes/(core)/dashboard/experience/index'
import { Route as coreDashboardEducationIndexRouteImport } from './routes/(core)/dashboard/education/index'
import { Route as coreDashboardCertificateIndexRouteImport } from './routes/(core)/dashboard/certificate/index'
import { Route as coreDashboardAchievementIndexRouteImport } from './routes/(core)/dashboard/achievement/index'
import { Route as coreDashboardTechStackCreateRouteImport } from './routes/(core)/dashboard/tech-stack/create'
import { Route as coreDashboardSocialLinksCreateRouteImport } from './routes/(core)/dashboard/social-links/create'
import { Route as coreDashboardProjectsCreateRouteImport } from './routes/(core)/dashboard/projects/create'
import { Route as coreDashboardExperienceCreateRouteImport } from './routes/(core)/dashboard/experience/create'
import { Route as coreDashboardEducationCreateRouteImport } from './routes/(core)/dashboard/education/create'
import { Route as coreDashboardCertificateCreateRouteImport } from './routes/(core)/dashboard/certificate/create'
import { Route as coreDashboardAchievementCreateRouteImport } from './routes/(core)/dashboard/achievement/create'
import { Route as coreDashboardTechStackTechStackIdEditRouteImport } from './routes/(core)/dashboard/tech-stack/$techStackId.edit'
import { Route as coreDashboardSocialLinksSocialLinkIdEditRouteImport } from './routes/(core)/dashboard/social-links/$socialLinkId.edit'
import { Route as coreDashboardProjectsProjectIdEditRouteImport } from './routes/(core)/dashboard/projects/$projectId.edit'
import { Route as coreDashboardExperienceExperienceIdEditRouteImport } from './routes/(core)/dashboard/experience/$experienceId.edit'
import { Route as coreDashboardEducationEducationIdEditRouteImport } from './routes/(core)/dashboard/education/$educationId.edit'
import { Route as coreDashboardCertificateCertificateIdEditRouteImport } from './routes/(core)/dashboard/certificate/$certificateId.edit'
import { Route as coreDashboardAchievementAchievementIdEditRouteImport } from './routes/(core)/dashboard/achievement/$achievementId.edit'

const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const coreDashboardRouteRoute = coreDashboardRouteRouteImport.update({
  id: '/(core)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const coreDashboardIndexRoute = coreDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => coreDashboardRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const coreDashboardTechStackIndexRoute =
  coreDashboardTechStackIndexRouteImport.update({
    id: '/tech-stack/',
    path: '/tech-stack/',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardSocialLinksIndexRoute =
  coreDashboardSocialLinksIndexRouteImport.update({
    id: '/social-links/',
    path: '/social-links/',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardSeoIndexRoute = coreDashboardSeoIndexRouteImport.update({
  id: '/seo/',
  path: '/seo/',
  getParentRoute: () => coreDashboardRouteRoute,
} as any)
const coreDashboardResumeIndexRoute =
  coreDashboardResumeIndexRouteImport.update({
    id: '/resume/',
    path: '/resume/',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardProjectsIndexRoute =
  coreDashboardProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardHeroIndexRoute = coreDashboardHeroIndexRouteImport.update({
  id: '/hero/',
  path: '/hero/',
  getParentRoute: () => coreDashboardRouteRoute,
} as any)
const coreDashboardExperienceIndexRoute =
  coreDashboardExperienceIndexRouteImport.update({
    id: '/experience/',
    path: '/experience/',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardEducationIndexRoute =
  coreDashboardEducationIndexRouteImport.update({
    id: '/education/',
    path: '/education/',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardCertificateIndexRoute =
  coreDashboardCertificateIndexRouteImport.update({
    id: '/certificate/',
    path: '/certificate/',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardAchievementIndexRoute =
  coreDashboardAchievementIndexRouteImport.update({
    id: '/achievement/',
    path: '/achievement/',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardTechStackCreateRoute =
  coreDashboardTechStackCreateRouteImport.update({
    id: '/tech-stack/create',
    path: '/tech-stack/create',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardSocialLinksCreateRoute =
  coreDashboardSocialLinksCreateRouteImport.update({
    id: '/social-links/create',
    path: '/social-links/create',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardProjectsCreateRoute =
  coreDashboardProjectsCreateRouteImport.update({
    id: '/projects/create',
    path: '/projects/create',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardExperienceCreateRoute =
  coreDashboardExperienceCreateRouteImport.update({
    id: '/experience/create',
    path: '/experience/create',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardEducationCreateRoute =
  coreDashboardEducationCreateRouteImport.update({
    id: '/education/create',
    path: '/education/create',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardCertificateCreateRoute =
  coreDashboardCertificateCreateRouteImport.update({
    id: '/certificate/create',
    path: '/certificate/create',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardAchievementCreateRoute =
  coreDashboardAchievementCreateRouteImport.update({
    id: '/achievement/create',
    path: '/achievement/create',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardTechStackTechStackIdEditRoute =
  coreDashboardTechStackTechStackIdEditRouteImport.update({
    id: '/tech-stack/$techStackId/edit',
    path: '/tech-stack/$techStackId/edit',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardSocialLinksSocialLinkIdEditRoute =
  coreDashboardSocialLinksSocialLinkIdEditRouteImport.update({
    id: '/social-links/$socialLinkId/edit',
    path: '/social-links/$socialLinkId/edit',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardProjectsProjectIdEditRoute =
  coreDashboardProjectsProjectIdEditRouteImport.update({
    id: '/projects/$projectId/edit',
    path: '/projects/$projectId/edit',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardExperienceExperienceIdEditRoute =
  coreDashboardExperienceExperienceIdEditRouteImport.update({
    id: '/experience/$experienceId/edit',
    path: '/experience/$experienceId/edit',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardEducationEducationIdEditRoute =
  coreDashboardEducationEducationIdEditRouteImport.update({
    id: '/education/$educationId/edit',
    path: '/education/$educationId/edit',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardCertificateCertificateIdEditRoute =
  coreDashboardCertificateCertificateIdEditRouteImport.update({
    id: '/certificate/$certificateId/edit',
    path: '/certificate/$certificateId/edit',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardAchievementAchievementIdEditRoute =
  coreDashboardAchievementAchievementIdEditRouteImport.update({
    id: '/achievement/$achievementId/edit',
    path: '/achievement/$achievementId/edit',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificates': typeof CertificatesRoute
  '/resume': typeof ResumeRoute
  '/dashboard': typeof coreDashboardRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/': typeof coreDashboardIndexRoute
  '/dashboard/achievement/create': typeof coreDashboardAchievementCreateRoute
  '/dashboard/certificate/create': typeof coreDashboardCertificateCreateRoute
  '/dashboard/education/create': typeof coreDashboardEducationCreateRoute
  '/dashboard/experience/create': typeof coreDashboardExperienceCreateRoute
  '/dashboard/projects/create': typeof coreDashboardProjectsCreateRoute
  '/dashboard/social-links/create': typeof coreDashboardSocialLinksCreateRoute
  '/dashboard/tech-stack/create': typeof coreDashboardTechStackCreateRoute
  '/dashboard/achievement/': typeof coreDashboardAchievementIndexRoute
  '/dashboard/certificate/': typeof coreDashboardCertificateIndexRoute
  '/dashboard/education/': typeof coreDashboardEducationIndexRoute
  '/dashboard/experience/': typeof coreDashboardExperienceIndexRoute
  '/dashboard/hero/': typeof coreDashboardHeroIndexRoute
  '/dashboard/projects/': typeof coreDashboardProjectsIndexRoute
  '/dashboard/resume/': typeof coreDashboardResumeIndexRoute
  '/dashboard/seo/': typeof coreDashboardSeoIndexRoute
  '/dashboard/social-links/': typeof coreDashboardSocialLinksIndexRoute
  '/dashboard/tech-stack/': typeof coreDashboardTechStackIndexRoute
  '/dashboard/achievement/$achievementId/edit': typeof coreDashboardAchievementAchievementIdEditRoute
  '/dashboard/certificate/$certificateId/edit': typeof coreDashboardCertificateCertificateIdEditRoute
  '/dashboard/education/$educationId/edit': typeof coreDashboardEducationEducationIdEditRoute
  '/dashboard/experience/$experienceId/edit': typeof coreDashboardExperienceExperienceIdEditRoute
  '/dashboard/projects/$projectId/edit': typeof coreDashboardProjectsProjectIdEditRoute
  '/dashboard/social-links/$socialLinkId/edit': typeof coreDashboardSocialLinksSocialLinkIdEditRoute
  '/dashboard/tech-stack/$techStackId/edit': typeof coreDashboardTechStackTechStackIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificates': typeof CertificatesRoute
  '/resume': typeof ResumeRoute
  '/login': typeof authLoginRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard': typeof coreDashboardIndexRoute
  '/dashboard/achievement/create': typeof coreDashboardAchievementCreateRoute
  '/dashboard/certificate/create': typeof coreDashboardCertificateCreateRoute
  '/dashboard/education/create': typeof coreDashboardEducationCreateRoute
  '/dashboard/experience/create': typeof coreDashboardExperienceCreateRoute
  '/dashboard/projects/create': typeof coreDashboardProjectsCreateRoute
  '/dashboard/social-links/create': typeof coreDashboardSocialLinksCreateRoute
  '/dashboard/tech-stack/create': typeof coreDashboardTechStackCreateRoute
  '/dashboard/achievement': typeof coreDashboardAchievementIndexRoute
  '/dashboard/certificate': typeof coreDashboardCertificateIndexRoute
  '/dashboard/education': typeof coreDashboardEducationIndexRoute
  '/dashboard/experience': typeof coreDashboardExperienceIndexRoute
  '/dashboard/hero': typeof coreDashboardHeroIndexRoute
  '/dashboard/projects': typeof coreDashboardProjectsIndexRoute
  '/dashboard/resume': typeof coreDashboardResumeIndexRoute
  '/dashboard/seo': typeof coreDashboardSeoIndexRoute
  '/dashboard/social-links': typeof coreDashboardSocialLinksIndexRoute
  '/dashboard/tech-stack': typeof coreDashboardTechStackIndexRoute
  '/dashboard/achievement/$achievementId/edit': typeof coreDashboardAchievementAchievementIdEditRoute
  '/dashboard/certificate/$certificateId/edit': typeof coreDashboardCertificateCertificateIdEditRoute
  '/dashboard/education/$educationId/edit': typeof coreDashboardEducationEducationIdEditRoute
  '/dashboard/experience/$experienceId/edit': typeof coreDashboardExperienceExperienceIdEditRoute
  '/dashboard/projects/$projectId/edit': typeof coreDashboardProjectsProjectIdEditRoute
  '/dashboard/social-links/$socialLinkId/edit': typeof coreDashboardSocialLinksSocialLinkIdEditRoute
  '/dashboard/tech-stack/$techStackId/edit': typeof coreDashboardTechStackTechStackIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/certificates': typeof CertificatesRoute
  '/resume': typeof ResumeRoute
  '/(core)/dashboard': typeof coreDashboardRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/(core)/dashboard/': typeof coreDashboardIndexRoute
  '/(core)/dashboard/achievement/create': typeof coreDashboardAchievementCreateRoute
  '/(core)/dashboard/certificate/create': typeof coreDashboardCertificateCreateRoute
  '/(core)/dashboard/education/create': typeof coreDashboardEducationCreateRoute
  '/(core)/dashboard/experience/create': typeof coreDashboardExperienceCreateRoute
  '/(core)/dashboard/projects/create': typeof coreDashboardProjectsCreateRoute
  '/(core)/dashboard/social-links/create': typeof coreDashboardSocialLinksCreateRoute
  '/(core)/dashboard/tech-stack/create': typeof coreDashboardTechStackCreateRoute
  '/(core)/dashboard/achievement/': typeof coreDashboardAchievementIndexRoute
  '/(core)/dashboard/certificate/': typeof coreDashboardCertificateIndexRoute
  '/(core)/dashboard/education/': typeof coreDashboardEducationIndexRoute
  '/(core)/dashboard/experience/': typeof coreDashboardExperienceIndexRoute
  '/(core)/dashboard/hero/': typeof coreDashboardHeroIndexRoute
  '/(core)/dashboard/projects/': typeof coreDashboardProjectsIndexRoute
  '/(core)/dashboard/resume/': typeof coreDashboardResumeIndexRoute
  '/(core)/dashboard/seo/': typeof coreDashboardSeoIndexRoute
  '/(core)/dashboard/social-links/': typeof coreDashboardSocialLinksIndexRoute
  '/(core)/dashboard/tech-stack/': typeof coreDashboardTechStackIndexRoute
  '/(core)/dashboard/achievement/$achievementId/edit': typeof coreDashboardAchievementAchievementIdEditRoute
  '/(core)/dashboard/certificate/$certificateId/edit': typeof coreDashboardCertificateCertificateIdEditRoute
  '/(core)/dashboard/education/$educationId/edit': typeof coreDashboardEducationEducationIdEditRoute
  '/(core)/dashboard/experience/$experienceId/edit': typeof coreDashboardExperienceExperienceIdEditRoute
  '/(core)/dashboard/projects/$projectId/edit': typeof coreDashboardProjectsProjectIdEditRoute
  '/(core)/dashboard/social-links/$socialLinkId/edit': typeof coreDashboardSocialLinksSocialLinkIdEditRoute
  '/(core)/dashboard/tech-stack/$techStackId/edit': typeof coreDashboardTechStackTechStackIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certificates'
    | '/resume'
    | '/dashboard'
    | '/login'
    | '/projects/$slug'
    | '/projects/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/'
    | '/dashboard/achievement/create'
    | '/dashboard/certificate/create'
    | '/dashboard/education/create'
    | '/dashboard/experience/create'
    | '/dashboard/projects/create'
    | '/dashboard/social-links/create'
    | '/dashboard/tech-stack/create'
    | '/dashboard/achievement/'
    | '/dashboard/certificate/'
    | '/dashboard/education/'
    | '/dashboard/experience/'
    | '/dashboard/hero/'
    | '/dashboard/projects/'
    | '/dashboard/resume/'
    | '/dashboard/seo/'
    | '/dashboard/social-links/'
    | '/dashboard/tech-stack/'
    | '/dashboard/achievement/$achievementId/edit'
    | '/dashboard/certificate/$certificateId/edit'
    | '/dashboard/education/$educationId/edit'
    | '/dashboard/experience/$experienceId/edit'
    | '/dashboard/projects/$projectId/edit'
    | '/dashboard/social-links/$socialLinkId/edit'
    | '/dashboard/tech-stack/$techStackId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificates'
    | '/resume'
    | '/login'
    | '/projects/$slug'
    | '/projects'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard'
    | '/dashboard/achievement/create'
    | '/dashboard/certificate/create'
    | '/dashboard/education/create'
    | '/dashboard/experience/create'
    | '/dashboard/projects/create'
    | '/dashboard/social-links/create'
    | '/dashboard/tech-stack/create'
    | '/dashboard/achievement'
    | '/dashboard/certificate'
    | '/dashboard/education'
    | '/dashboard/experience'
    | '/dashboard/hero'
    | '/dashboard/projects'
    | '/dashboard/resume'
    | '/dashboard/seo'
    | '/dashboard/social-links'
    | '/dashboard/tech-stack'
    | '/dashboard/achievement/$achievementId/edit'
    | '/dashboard/certificate/$certificateId/edit'
    | '/dashboard/education/$educationId/edit'
    | '/dashboard/experience/$experienceId/edit'
    | '/dashboard/projects/$projectId/edit'
    | '/dashboard/social-links/$socialLinkId/edit'
    | '/dashboard/tech-stack/$techStackId/edit'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/certificates'
    | '/resume'
    | '/(core)/dashboard'
    | '/(auth)/login'
    | '/projects/$slug'
    | '/projects/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/(core)/dashboard/'
    | '/(core)/dashboard/achievement/create'
    | '/(core)/dashboard/certificate/create'
    | '/(core)/dashboard/education/create'
    | '/(core)/dashboard/experience/create'
    | '/(core)/dashboard/projects/create'
    | '/(core)/dashboard/social-links/create'
    | '/(core)/dashboard/tech-stack/create'
    | '/(core)/dashboard/achievement/'
    | '/(core)/dashboard/certificate/'
    | '/(core)/dashboard/education/'
    | '/(core)/dashboard/experience/'
    | '/(core)/dashboard/hero/'
    | '/(core)/dashboard/projects/'
    | '/(core)/dashboard/resume/'
    | '/(core)/dashboard/seo/'
    | '/(core)/dashboard/social-links/'
    | '/(core)/dashboard/tech-stack/'
    | '/(core)/dashboard/achievement/$achievementId/edit'
    | '/(core)/dashboard/certificate/$certificateId/edit'
    | '/(core)/dashboard/education/$educationId/edit'
    | '/(core)/dashboard/experience/$experienceId/edit'
    | '/(core)/dashboard/projects/$projectId/edit'
    | '/(core)/dashboard/social-links/$socialLinkId/edit'
    | '/(core)/dashboard/tech-stack/$techStackId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  CertificatesRoute: typeof CertificatesRoute
  ResumeRoute: typeof ResumeRoute
  coreDashboardRouteRoute: typeof coreDashboardRouteRouteWithChildren
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(core)/dashboard': {
      id: '/(core)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof coreDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(core)/dashboard/': {
      id: '/(core)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof coreDashboardIndexRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(core)/dashboard/tech-stack/': {
      id: '/(core)/dashboard/tech-stack/'
      path: '/tech-stack'
      fullPath: '/dashboard/tech-stack/'
      preLoaderRoute: typeof coreDashboardTechStackIndexRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/social-links/': {
      id: '/(core)/dashboard/social-links/'
      path: '/social-links'
      fullPath: '/dashboard/social-links/'
      preLoaderRoute: typeof coreDashboardSocialLinksIndexRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/seo/': {
      id: '/(core)/dashboard/seo/'
      path: '/seo'
      fullPath: '/dashboard/seo/'
      preLoaderRoute: typeof coreDashboardSeoIndexRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/resume/': {
      id: '/(core)/dashboard/resume/'
      path: '/resume'
      fullPath: '/dashboard/resume/'
      preLoaderRoute: typeof coreDashboardResumeIndexRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/projects/': {
      id: '/(core)/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof coreDashboardProjectsIndexRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/hero/': {
      id: '/(core)/dashboard/hero/'
      path: '/hero'
      fullPath: '/dashboard/hero/'
      preLoaderRoute: typeof coreDashboardHeroIndexRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/experience/': {
      id: '/(core)/dashboard/experience/'
      path: '/experience'
      fullPath: '/dashboard/experience/'
      preLoaderRoute: typeof coreDashboardExperienceIndexRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/education/': {
      id: '/(core)/dashboard/education/'
      path: '/education'
      fullPath: '/dashboard/education/'
      preLoaderRoute: typeof coreDashboardEducationIndexRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/certificate/': {
      id: '/(core)/dashboard/certificate/'
      path: '/certificate'
      fullPath: '/dashboard/certificate/'
      preLoaderRoute: typeof coreDashboardCertificateIndexRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/achievement/': {
      id: '/(core)/dashboard/achievement/'
      path: '/achievement'
      fullPath: '/dashboard/achievement/'
      preLoaderRoute: typeof coreDashboardAchievementIndexRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/tech-stack/create': {
      id: '/(core)/dashboard/tech-stack/create'
      path: '/tech-stack/create'
      fullPath: '/dashboard/tech-stack/create'
      preLoaderRoute: typeof coreDashboardTechStackCreateRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/social-links/create': {
      id: '/(core)/dashboard/social-links/create'
      path: '/social-links/create'
      fullPath: '/dashboard/social-links/create'
      preLoaderRoute: typeof coreDashboardSocialLinksCreateRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/projects/create': {
      id: '/(core)/dashboard/projects/create'
      path: '/projects/create'
      fullPath: '/dashboard/projects/create'
      preLoaderRoute: typeof coreDashboardProjectsCreateRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/experience/create': {
      id: '/(core)/dashboard/experience/create'
      path: '/experience/create'
      fullPath: '/dashboard/experience/create'
      preLoaderRoute: typeof coreDashboardExperienceCreateRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/education/create': {
      id: '/(core)/dashboard/education/create'
      path: '/education/create'
      fullPath: '/dashboard/education/create'
      preLoaderRoute: typeof coreDashboardEducationCreateRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/certificate/create': {
      id: '/(core)/dashboard/certificate/create'
      path: '/certificate/create'
      fullPath: '/dashboard/certificate/create'
      preLoaderRoute: typeof coreDashboardCertificateCreateRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/achievement/create': {
      id: '/(core)/dashboard/achievement/create'
      path: '/achievement/create'
      fullPath: '/dashboard/achievement/create'
      preLoaderRoute: typeof coreDashboardAchievementCreateRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/tech-stack/$techStackId/edit': {
      id: '/(core)/dashboard/tech-stack/$techStackId/edit'
      path: '/tech-stack/$techStackId/edit'
      fullPath: '/dashboard/tech-stack/$techStackId/edit'
      preLoaderRoute: typeof coreDashboardTechStackTechStackIdEditRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/social-links/$socialLinkId/edit': {
      id: '/(core)/dashboard/social-links/$socialLinkId/edit'
      path: '/social-links/$socialLinkId/edit'
      fullPath: '/dashboard/social-links/$socialLinkId/edit'
      preLoaderRoute: typeof coreDashboardSocialLinksSocialLinkIdEditRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/projects/$projectId/edit': {
      id: '/(core)/dashboard/projects/$projectId/edit'
      path: '/projects/$projectId/edit'
      fullPath: '/dashboard/projects/$projectId/edit'
      preLoaderRoute: typeof coreDashboardProjectsProjectIdEditRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/experience/$experienceId/edit': {
      id: '/(core)/dashboard/experience/$experienceId/edit'
      path: '/experience/$experienceId/edit'
      fullPath: '/dashboard/experience/$experienceId/edit'
      preLoaderRoute: typeof coreDashboardExperienceExperienceIdEditRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/education/$educationId/edit': {
      id: '/(core)/dashboard/education/$educationId/edit'
      path: '/education/$educationId/edit'
      fullPath: '/dashboard/education/$educationId/edit'
      preLoaderRoute: typeof coreDashboardEducationEducationIdEditRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/certificate/$certificateId/edit': {
      id: '/(core)/dashboard/certificate/$certificateId/edit'
      path: '/certificate/$certificateId/edit'
      fullPath: '/dashboard/certificate/$certificateId/edit'
      preLoaderRoute: typeof coreDashboardCertificateCertificateIdEditRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/achievement/$achievementId/edit': {
      id: '/(core)/dashboard/achievement/$achievementId/edit'
      path: '/achievement/$achievementId/edit'
      fullPath: '/dashboard/achievement/$achievementId/edit'
      preLoaderRoute: typeof coreDashboardAchievementAchievementIdEditRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface coreDashboardRouteRouteChildren {
  coreDashboardIndexRoute: typeof coreDashboardIndexRoute
  coreDashboardAchievementCreateRoute: typeof coreDashboardAchievementCreateRoute
  coreDashboardCertificateCreateRoute: typeof coreDashboardCertificateCreateRoute
  coreDashboardEducationCreateRoute: typeof coreDashboardEducationCreateRoute
  coreDashboardExperienceCreateRoute: typeof coreDashboardExperienceCreateRoute
  coreDashboardProjectsCreateRoute: typeof coreDashboardProjectsCreateRoute
  coreDashboardSocialLinksCreateRoute: typeof coreDashboardSocialLinksCreateRoute
  coreDashboardTechStackCreateRoute: typeof coreDashboardTechStackCreateRoute
  coreDashboardAchievementIndexRoute: typeof coreDashboardAchievementIndexRoute
  coreDashboardCertificateIndexRoute: typeof coreDashboardCertificateIndexRoute
  coreDashboardEducationIndexRoute: typeof coreDashboardEducationIndexRoute
  coreDashboardExperienceIndexRoute: typeof coreDashboardExperienceIndexRoute
  coreDashboardHeroIndexRoute: typeof coreDashboardHeroIndexRoute
  coreDashboardProjectsIndexRoute: typeof coreDashboardProjectsIndexRoute
  coreDashboardResumeIndexRoute: typeof coreDashboardResumeIndexRoute
  coreDashboardSeoIndexRoute: typeof coreDashboardSeoIndexRoute
  coreDashboardSocialLinksIndexRoute: typeof coreDashboardSocialLinksIndexRoute
  coreDashboardTechStackIndexRoute: typeof coreDashboardTechStackIndexRoute
  coreDashboardAchievementAchievementIdEditRoute: typeof coreDashboardAchievementAchievementIdEditRoute
  coreDashboardCertificateCertificateIdEditRoute: typeof coreDashboardCertificateCertificateIdEditRoute
  coreDashboardEducationEducationIdEditRoute: typeof coreDashboardEducationEducationIdEditRoute
  coreDashboardExperienceExperienceIdEditRoute: typeof coreDashboardExperienceExperienceIdEditRoute
  coreDashboardProjectsProjectIdEditRoute: typeof coreDashboardProjectsProjectIdEditRoute
  coreDashboardSocialLinksSocialLinkIdEditRoute: typeof coreDashboardSocialLinksSocialLinkIdEditRoute
  coreDashboardTechStackTechStackIdEditRoute: typeof coreDashboardTechStackTechStackIdEditRoute
}

const coreDashboardRouteRouteChildren: coreDashboardRouteRouteChildren = {
  coreDashboardIndexRoute: coreDashboardIndexRoute,
  coreDashboardAchievementCreateRoute: coreDashboardAchievementCreateRoute,
  coreDashboardCertificateCreateRoute: coreDashboardCertificateCreateRoute,
  coreDashboardEducationCreateRoute: coreDashboardEducationCreateRoute,
  coreDashboardExperienceCreateRoute: coreDashboardExperienceCreateRoute,
  coreDashboardProjectsCreateRoute: coreDashboardProjectsCreateRoute,
  coreDashboardSocialLinksCreateRoute: coreDashboardSocialLinksCreateRoute,
  coreDashboardTechStackCreateRoute: coreDashboardTechStackCreateRoute,
  coreDashboardAchievementIndexRoute: coreDashboardAchievementIndexRoute,
  coreDashboardCertificateIndexRoute: coreDashboardCertificateIndexRoute,
  coreDashboardEducationIndexRoute: coreDashboardEducationIndexRoute,
  coreDashboardExperienceIndexRoute: coreDashboardExperienceIndexRoute,
  coreDashboardHeroIndexRoute: coreDashboardHeroIndexRoute,
  coreDashboardProjectsIndexRoute: coreDashboardProjectsIndexRoute,
  coreDashboardResumeIndexRoute: coreDashboardResumeIndexRoute,
  coreDashboardSeoIndexRoute: coreDashboardSeoIndexRoute,
  coreDashboardSocialLinksIndexRoute: coreDashboardSocialLinksIndexRoute,
  coreDashboardTechStackIndexRoute: coreDashboardTechStackIndexRoute,
  coreDashboardAchievementAchievementIdEditRoute:
    coreDashboardAchievementAchievementIdEditRoute,
  coreDashboardCertificateCertificateIdEditRoute:
    coreDashboardCertificateCertificateIdEditRoute,
  coreDashboardEducationEducationIdEditRoute:
    coreDashboardEducationEducationIdEditRoute,
  coreDashboardExperienceExperienceIdEditRoute:
    coreDashboardExperienceExperienceIdEditRoute,
  coreDashboardProjectsProjectIdEditRoute:
    coreDashboardProjectsProjectIdEditRoute,
  coreDashboardSocialLinksSocialLinkIdEditRoute:
    coreDashboardSocialLinksSocialLinkIdEditRoute,
  coreDashboardTechStackTechStackIdEditRoute:
    coreDashboardTechStackTechStackIdEditRoute,
}

const coreDashboardRouteRouteWithChildren =
  coreDashboardRouteRoute._addFileChildren(coreDashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  CertificatesRoute: CertificatesRoute,
  ResumeRoute: ResumeRoute,
  coreDashboardRouteRoute: coreDashboardRouteRouteWithChildren,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
