/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as coreDashboardRouteRouteImport } from './routes/(core)/dashboard/route'
import { Route as coreDashboardIndexRouteImport } from './routes/(core)/dashboard/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as coreDashboardTechStackIndexRouteImport } from './routes/(core)/dashboard/tech-stack/index'
import { Route as coreDashboardSocialLinksIndexRouteImport } from './routes/(core)/dashboard/social-links/index'
import { Route as coreDashboardProjectsIndexRouteImport } from './routes/(core)/dashboard/projects/index'
import { Route as coreDashboardHeroIndexRouteImport } from './routes/(core)/dashboard/hero/index'
import { Route as coreDashboardExperienceIndexRouteImport } from './routes/(core)/dashboard/experience/index'
import { Route as coreDashboardCertificateIndexRouteImport } from './routes/(core)/dashboard/certificate/index'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const coreDashboardRouteRoute = coreDashboardRouteRouteImport.update({
  id: '/(core)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const coreDashboardIndexRoute = coreDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => coreDashboardRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const coreDashboardTechStackIndexRoute =
  coreDashboardTechStackIndexRouteImport.update({
    id: '/tech-stack/',
    path: '/tech-stack/',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardSocialLinksIndexRoute =
  coreDashboardSocialLinksIndexRouteImport.update({
    id: '/social-links/',
    path: '/social-links/',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardProjectsIndexRoute =
  coreDashboardProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardHeroIndexRoute = coreDashboardHeroIndexRouteImport.update({
  id: '/hero/',
  path: '/hero/',
  getParentRoute: () => coreDashboardRouteRoute,
} as any)
const coreDashboardExperienceIndexRoute =
  coreDashboardExperienceIndexRouteImport.update({
    id: '/experience/',
    path: '/experience/',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)
const coreDashboardCertificateIndexRoute =
  coreDashboardCertificateIndexRouteImport.update({
    id: '/certificate/',
    path: '/certificate/',
    getParentRoute: () => coreDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificates': typeof CertificatesRoute
  '/projects': typeof ProjectsRoute
  '/dashboard': typeof coreDashboardRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/': typeof coreDashboardIndexRoute
  '/dashboard/certificate/': typeof coreDashboardCertificateIndexRoute
  '/dashboard/experience/': typeof coreDashboardExperienceIndexRoute
  '/dashboard/hero/': typeof coreDashboardHeroIndexRoute
  '/dashboard/projects/': typeof coreDashboardProjectsIndexRoute
  '/dashboard/social-links/': typeof coreDashboardSocialLinksIndexRoute
  '/dashboard/tech-stack/': typeof coreDashboardTechStackIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificates': typeof CertificatesRoute
  '/projects': typeof ProjectsRoute
  '/login': typeof authLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard': typeof coreDashboardIndexRoute
  '/dashboard/certificate': typeof coreDashboardCertificateIndexRoute
  '/dashboard/experience': typeof coreDashboardExperienceIndexRoute
  '/dashboard/hero': typeof coreDashboardHeroIndexRoute
  '/dashboard/projects': typeof coreDashboardProjectsIndexRoute
  '/dashboard/social-links': typeof coreDashboardSocialLinksIndexRoute
  '/dashboard/tech-stack': typeof coreDashboardTechStackIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/certificates': typeof CertificatesRoute
  '/projects': typeof ProjectsRoute
  '/(core)/dashboard': typeof coreDashboardRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/(core)/dashboard/': typeof coreDashboardIndexRoute
  '/(core)/dashboard/certificate/': typeof coreDashboardCertificateIndexRoute
  '/(core)/dashboard/experience/': typeof coreDashboardExperienceIndexRoute
  '/(core)/dashboard/hero/': typeof coreDashboardHeroIndexRoute
  '/(core)/dashboard/projects/': typeof coreDashboardProjectsIndexRoute
  '/(core)/dashboard/social-links/': typeof coreDashboardSocialLinksIndexRoute
  '/(core)/dashboard/tech-stack/': typeof coreDashboardTechStackIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certificates'
    | '/projects'
    | '/dashboard'
    | '/login'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/'
    | '/dashboard/certificate/'
    | '/dashboard/experience/'
    | '/dashboard/hero/'
    | '/dashboard/projects/'
    | '/dashboard/social-links/'
    | '/dashboard/tech-stack/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificates'
    | '/projects'
    | '/login'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard'
    | '/dashboard/certificate'
    | '/dashboard/experience'
    | '/dashboard/hero'
    | '/dashboard/projects'
    | '/dashboard/social-links'
    | '/dashboard/tech-stack'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/certificates'
    | '/projects'
    | '/(core)/dashboard'
    | '/(auth)/login'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/(core)/dashboard/'
    | '/(core)/dashboard/certificate/'
    | '/(core)/dashboard/experience/'
    | '/(core)/dashboard/hero/'
    | '/(core)/dashboard/projects/'
    | '/(core)/dashboard/social-links/'
    | '/(core)/dashboard/tech-stack/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  CertificatesRoute: typeof CertificatesRoute
  ProjectsRoute: typeof ProjectsRoute
  coreDashboardRouteRoute: typeof coreDashboardRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(core)/dashboard': {
      id: '/(core)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof coreDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(core)/dashboard/': {
      id: '/(core)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof coreDashboardIndexRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(core)/dashboard/tech-stack/': {
      id: '/(core)/dashboard/tech-stack/'
      path: '/tech-stack'
      fullPath: '/dashboard/tech-stack/'
      preLoaderRoute: typeof coreDashboardTechStackIndexRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/social-links/': {
      id: '/(core)/dashboard/social-links/'
      path: '/social-links'
      fullPath: '/dashboard/social-links/'
      preLoaderRoute: typeof coreDashboardSocialLinksIndexRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/projects/': {
      id: '/(core)/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof coreDashboardProjectsIndexRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/hero/': {
      id: '/(core)/dashboard/hero/'
      path: '/hero'
      fullPath: '/dashboard/hero/'
      preLoaderRoute: typeof coreDashboardHeroIndexRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/experience/': {
      id: '/(core)/dashboard/experience/'
      path: '/experience'
      fullPath: '/dashboard/experience/'
      preLoaderRoute: typeof coreDashboardExperienceIndexRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
    '/(core)/dashboard/certificate/': {
      id: '/(core)/dashboard/certificate/'
      path: '/certificate'
      fullPath: '/dashboard/certificate/'
      preLoaderRoute: typeof coreDashboardCertificateIndexRouteImport
      parentRoute: typeof coreDashboardRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface coreDashboardRouteRouteChildren {
  coreDashboardIndexRoute: typeof coreDashboardIndexRoute
  coreDashboardCertificateIndexRoute: typeof coreDashboardCertificateIndexRoute
  coreDashboardExperienceIndexRoute: typeof coreDashboardExperienceIndexRoute
  coreDashboardHeroIndexRoute: typeof coreDashboardHeroIndexRoute
  coreDashboardProjectsIndexRoute: typeof coreDashboardProjectsIndexRoute
  coreDashboardSocialLinksIndexRoute: typeof coreDashboardSocialLinksIndexRoute
  coreDashboardTechStackIndexRoute: typeof coreDashboardTechStackIndexRoute
}

const coreDashboardRouteRouteChildren: coreDashboardRouteRouteChildren = {
  coreDashboardIndexRoute: coreDashboardIndexRoute,
  coreDashboardCertificateIndexRoute: coreDashboardCertificateIndexRoute,
  coreDashboardExperienceIndexRoute: coreDashboardExperienceIndexRoute,
  coreDashboardHeroIndexRoute: coreDashboardHeroIndexRoute,
  coreDashboardProjectsIndexRoute: coreDashboardProjectsIndexRoute,
  coreDashboardSocialLinksIndexRoute: coreDashboardSocialLinksIndexRoute,
  coreDashboardTechStackIndexRoute: coreDashboardTechStackIndexRoute,
}

const coreDashboardRouteRouteWithChildren =
  coreDashboardRouteRoute._addFileChildren(coreDashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  CertificatesRoute: CertificatesRoute,
  ProjectsRoute: ProjectsRoute,
  coreDashboardRouteRoute: coreDashboardRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
